name: Update NordVPN OpenVPN config files

on:
  push:
  schedule:
    - cron: 0 3 * * *

jobs:
  update_ovpn:
    name: Update NordVPN OpenVPN config files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.5

      - name: Update template.ovpn
        id: downloadovpn
        shell: bash
        run: |
          wget -q https://downloads.nordcdn.com/configs/archives/servers/ovpn.zip -qO /tmp/ovpn.zip
          unzip -q /tmp/ovpn.zip -d /tmp/ovpn

          RANDOMFILE=$(find /tmp/ovpn -type f | shuf -n 1)
          echo "Use ${RANDOMFILE} as base for template template.ovpn"
          cp ${RANDOMFILE} root/etc/nordvpn/template.ovpn
          sed -i '/proto /c\proto __PROTOCOL__' root/etc/nordvpn/template.ovpn
          sed -i '/remote /c\remote __IP__ __PORT__' root/etc/nordvpn/template.ovpn

          DATE=$(date +%y%m%d)
          echo "::set-output name=date::${DATE}"

          MD5=($(md5sum /tmp/ovpn.zip))
          PR_BRANCH="ovpnupdaterbot/ovpnupdate-${MD5}"
          echo "::set-output name=pr_branch::${PR_BRANCH}"

          echo "Base pr_branch=${PR_BRANCH}, date=${DATE}"

      - name: Create Pull Request, update template.ovpn, date ${{ steps.downloadovpn.outputs.date }}
        uses: peter-evans/create-pull-request@v3.10.1
        with:
          branch: ${{ steps.downloadovpn.outputs.pr_branch }}
          commit-message: Update template.ovpn, date ${{ steps.downloadovpn.outputs.date }}
          delete-branch: true
          title: Update template.ovpn, date ${{ steps.downloadovpn.outputs.date }}
          body: |
            Update template.ovpn, date ${{ steps.downloadovpn.outputs.date }}

            - Auto-generated by [create-pull-request](https://github.com/peter-evans/create-pull-request)
          labels: |
            dependencies
            github_actions
