name: Update config files

on:
  schedule:
    - cron: 0 3 * * *

jobs:
  update_ovpn:
    name: Update OpenVPN template file
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Update template.ovpn
        id: downloadovpn
        shell: bash
        run: |
          wget -q https://downloads.nordcdn.com/configs/archives/servers/ovpn.zip -qO /tmp/ovpn.zip
          unzip -q /tmp/ovpn.zip -d /tmp/ovpn

          RANDOMFILE=$(find /tmp/ovpn -type f | shuf -n 1)
          echo "Use ${RANDOMFILE} as base for template template.ovpn"
          cp ${RANDOMFILE} root/etc/nordvpn/template.ovpn
          sed -i '/proto /c\proto __PROTOCOL__' root/etc/nordvpn/template.ovpn
          sed -i '/remote /c\remote __IP__ __PORT__' root/etc/nordvpn/template.ovpn

          DATE=$(date +%y%m%d)
          echo "::set-output name=date::${DATE}"

          echo "Base date=${DATE}"

      - name: Create Pull Request, update template.ovpn, date ${{ steps.downloadovpn.outputs.date }}
        uses: peter-evans/create-pull-request@v3.11.0
        with:
          branch: ovpnupdaterbot/ovpnupdate
          commit-message: Update template.ovpn, date ${{ steps.downloadovpn.outputs.date }}
          delete-branch: true
          title: Update template.ovpn, date ${{ steps.downloadovpn.outputs.date }}
          body: |
            Update template.ovpn, date ${{ steps.downloadovpn.outputs.date }}

            - Auto-generated by [create-pull-request](https://github.com/peter-evans/create-pull-request)
          labels: |
            dependencies
            github_actions

  update_jsons:
    name: Update json file
    runs-on: ubuntu-latest
    strategy:
      matrix:
        url: ["https://api.nordvpn.com/v1/servers/countries","https://api.nordvpn.com/v1/servers/groups","https://api.nordvpn.com/v1/technologies"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Get file name
        id: file
        shell: bash
        run: |
          URL=${{ matrix.url }}
          NAME=$(echo ${URL##*/})

          echo "::set-output name=name::${NAME}"

          echo "Base name=${NAME}"

      - name: Update ${{ steps.file.outputs.name }}.json
        id: getjson
        shell: bash
        run: |
          curl -s ${{ matrix.url }} | jq '.' > root/etc/nordvpn/${{ steps.file.outputs.name }}.json

          DATE=$(date +%y%m%d)
          echo "::set-output name=date::${DATE}"

          echo "Base date=${DATE}"

      - name: Create Pull Request, update ${{ steps.file.outputs.name }}.json, date ${{ steps.getjson.outputs.date }}
        uses: peter-evans/create-pull-request@v3.11.0
        with:
          branch: ovpnupdaterbot/${{ steps.file.outputs.name }}json
          commit-message: Update ${{ steps.file.outputs.name }}.json, date ${{ steps.getjson.outputs.date }}
          delete-branch: true
          title: Update ${{ steps.file.outputs.name }}.json, date ${{ steps.getjson.outputs.date }}
          body: |
            Update ${{ steps.file.outputs.name }}.json, date ${{ steps.getjson.outputs.date }}

            - Auto-generated by [create-pull-request](https://github.com/peter-evans/create-pull-request)
          labels: |
            dependencies
            github_actions
